### ISSUE TITLE
Can't implement the algorithm from README

### ISSUE THREAD

**Issue by ehpc** [FluorineDog/square_sum#1]
Hi, @FluorineDog !
I'm trying to implement your algorithm in JS. As I understand to compute a valid permutation for *N* you should first compute all permutations for *1..N-1*. 

The problem is my implementation doesn't always return valid result in reasonable time. Even if *z* is 1 000 000 it sometimes isn't enough. In the README you said it should take several iterations. So it seems my code is bad but I just can't understand why. Maybe you can point me in the right direction? I'd really appreciate it.

```javascript
function compute(n) {
  const strategiesCombinations = combine([swap, reverseA, reverseB]);
  let a = precomputed[n - 1];
  let b = [n];
  for (let z = 0; z < 100000; z++) {
    // 1. swap A and B or not 2. reverse A or not 3. reverse B or not
    strategiesCombinations[rnd(0, strategiesCombinations.length - 1)].forEach(strategy => {
      [a, b] = strategy(a, b);
    });
    // Split A into C, D,  where the last number of C and the first number of B sum to a square number.
    // A' = concat(C, B), B' = D, we got a new pair of valid arrays.
    const validSplits = [];
    for (let i = 0; i < a.length; i++) {
      if (isSquare(a[i] + b[0])) {
        validSplits.push(i);
      }
    }
    const splitIndex = validSplits[rnd(0, validSplits.length - 1)];
    const c = a.slice(0, splitIndex + 1);
    const d = a.slice(splitIndex + 1);
    a = c.concat(b);
    b = d;
    // Finally, check if any endpoint of A and any endpoint of B can sum to a square number. If so, concatenate them accordingly, 
    // and return the result. if not, go on for the next iteration.
    if (isSquare(a[0] + b[0])) {
      const res = b.slice().reverse().concat(a);
      if (test(res)) return cache(n, res);
    }
    if (isSquare(a[0] + b[b.length - 1])) {
      const res = b.concat(a);
      if (test(res)) return cache(n, res);
    }
    if (isSquare(a[a.length - 1] + b[0])) {
      const res = a.concat(b);
      if (test(res)) return cache(n, res);
    }
    if (isSquare(a[a.length - 1] + b[b.length - 1])) {
      const res = a.concat(b.slice().reverse());
      if (test(res)) return cache(n, res);
    }
  }
  return false;
}
```

**Comment by ehpc** [comment]
Sorry, found an error. I wasn't checking all endpoints :)

**Comment by FluorineDog** [comment]
Sorry, I didn't expect that someone would actually re-implement my algorithm, so I just wrote it vaguely, only clear enough to explain my own code.

At each iteration, there is high possibility that one of the many valid moves will lead to a final solution. Since checking an answer is fairly cheap, just do it to avoid too many iterations.

For the termination, please notice that there  are no square sum solution for N={2-14, 18-22, 24}, so you may be stuck at computing 24 from N=23, since my algorithm won't terminate at no solution case. Apart from that, if you start from N=25, my code should work fine. 

Enjoy. Have a nice day!
